apiVersion: v1
kind: Pod
metadata:
  name: config-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env"]
      env:
      - name: STUDENT_NAME
        value: "Your Name"
      - name: SCHOOL
        value: "Linux Acacdemy"
      - name: KUBERNETES
        value: "is awesome"
  restartPolicy: Never

