--- # the job file sleeps for 10 seconds using a busybox container
apiVersion: batch/v1
kind: Job
metadata:
  name: sleep.busybox
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 4
